import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { DataQualityPanel } from '@/components/market/DataQualityPanel';
import { IndicatorGrid } from '@/components/market/IndicatorGrid';
import { OscillatorChart } from '@/components/market/OscillatorChart';
import { PriceChart } from '@/components/market/PriceChart';
import { SessionPanel } from '@/components/market/SessionPanel';
import { SERIES_COLORS, num } from '@/components/market/chart-primitives';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { api } from '@/lib/api';
import { cn } from '@/lib/utils';
import type {
  CalendarView,
  CandleSeries,
  IndicatorSnapshot,
  InstrumentList,
  QualityReport,
  TradabilityVerdict,
} from '@/lib/types';

const TIMEFRAMES = ['5m', '1d'] as const;

interface IndicatorSeriesResponse {
  length: number;
  sma20: (string | null)[];
  sma50: (string | null)[];
  bollingerUpper: (string | null)[];
  bollingerLower: (string | null)[];
  rsi14: (string | null)[];
  macd: (string | null)[];
  macdSignal: (string | null)[];
  macdHistogram: (string | null)[];
}

/**
 * The market-data view.
 *
 * Everything on this page is read-only, and deliberately so: there is no route
 * in the API that can place an order, and this page is not a trading screen.
 * It is where the provider adapter, the quality layer, the market calendar and
 * the indicator engine become visible.
 */
export function MarketPage() {
  const [symbol, setSymbol] = useState('AAPL');
  const [timeframe, setTimeframe] = useState<(typeof TIMEFRAMES)[number]>('5m');

  const { data: instruments } = useQuery({
    queryKey: ['market', 'instruments'],
    queryFn: () => api<InstrumentList>('/api/market-data/instruments'),
    staleTime: 60_000,
  });

  const { data: candles } = useQuery({
    queryKey: ['market', 'candles', symbol, timeframe],
    queryFn: () =>
      api<CandleSeries>(`/api/market-data/${symbol}/candles?timeframe=${timeframe}&limit=200`),
  });

  const { data: series } = useQuery({
    queryKey: ['market', 'series', symbol, timeframe],
    queryFn: () =>
      api<IndicatorSeriesResponse>(
        `/api/market-data/${symbol}/indicator-series?timeframe=${timeframe}&limit=200`,
      ),
  });

  const { data: snapshot } = useQuery({
    queryKey: ['market', 'indicators', symbol, timeframe],
    queryFn: () =>
      api<IndicatorSnapshot | null>(
        `/api/market-data/${symbol}/indicators?timeframe=${timeframe}&limit=200`,
      ),
  });

  const { data: quality } = useQuery({
    queryKey: ['market', 'quality'],
    queryFn: () => api<QualityReport>('/api/market-data/quality'),
    refetchInterval: 30_000,
  });

  const { data: calendar } = useQuery({
    queryKey: ['market', 'calendar'],
    queryFn: () => api<CalendarView>('/api/market-data/calendar/XNYS'),
    refetchInterval: 60_000,
  });

  const { data: tradability } = useQuery({
    queryKey: ['market', 'tradable', symbol],
    queryFn: () => api<TradabilityVerdict>(`/api/market-data/${symbol}/tradable`),
    refetchInterval: 60_000,
  });

  const toNumbers = (values: (string | null)[] | undefined): (number | null)[] =>
    (values ?? []).map((v) => num(v));

  const isSimulated = instruments?.provider === 'demo-simulator';

  return (
    <main className="mx-auto w-full max-w-7xl space-y-3 px-3 py-4 sm:px-6">
      {/* Provenance first. A page of prices that does not say where they came
          from is the single most misleading thing this app could show. */}
      {instruments && (
        <div
          className={cn(
            'flex flex-wrap items-center gap-2 rounded-md border px-3 py-2 text-xs',
            isSimulated ? 'border-sky-500/30 bg-sky-500/5' : 'border-border bg-muted/40',
          )}
        >
          <Badge variant={isSimulated ? 'default' : 'success'}>
            {isSimulated ? 'SIMULATED DATA' : instruments.provider.toUpperCase()}
          </Badge>
          <span className="text-muted-foreground">
            {isSimulated
              ? 'Prices are generated by the deterministic demo simulator, not a market feed. ' +
                'The quality layer, calendar and indicator engine below are the real ones — ' +
                'only the source is synthetic.'
              : instruments.isDelayed
                ? 'Delayed feed. A delayed price must never authorise a live entry.'
                : 'Real-time feed.'}
          </span>
        </div>
      )}

      <div className="grid gap-3 lg:grid-cols-[220px_minmax(0,1fr)]">
        <Card className="lg:sticky lg:top-16 lg:self-start">
          <CardHeader>
            <CardTitle>Symbols</CardTitle>
          </CardHeader>
          <CardContent className="space-y-0.5">
            {(instruments?.instruments ?? []).map((instrument) => (
              <button
                key={instrument.symbol}
                type="button"
                onClick={() => setSymbol(instrument.symbol)}
                className={cn(
                  'flex w-full items-baseline justify-between rounded-md px-2 py-1.5 text-left text-sm transition-colors',
                  instrument.symbol === symbol
                    ? 'bg-muted text-foreground'
                    : 'text-muted-foreground hover:bg-muted/60',
                )}
                aria-current={instrument.symbol === symbol}
              >
                <span className="font-medium">{instrument.symbol}</span>
                <span className="text-xs tabular-nums">{instrument.lastClose ?? '—'}</span>
              </button>
            ))}
            {instruments?.instruments.length === 0 && (
              <p className="text-xs text-muted-foreground">
                No instruments yet. Run <code>npm run backfill:demo</code>.
              </p>
            )}
          </CardContent>
        </Card>

        <div className="space-y-3">
          <div className="flex items-center gap-1">
            {TIMEFRAMES.map((tf) => (
              <button
                key={tf}
                type="button"
                onClick={() => setTimeframe(tf)}
                className={cn(
                  'rounded-md px-2.5 py-1 text-xs transition-colors',
                  tf === timeframe
                    ? 'bg-muted text-foreground'
                    : 'text-muted-foreground hover:bg-muted/60',
                )}
                aria-current={tf === timeframe}
              >
                {tf}
              </button>
            ))}
          </div>

          <PriceChart
            symbol={symbol}
            timeframe={timeframe}
            candles={candles?.candles ?? []}
            provider={candles?.candles[0]?.provider ?? 'no data'}
            overlays={{
              sma20: toNumbers(series?.sma20),
              sma50: toNumbers(series?.sma50),
              bollingerUpper: toNumbers(series?.bollingerUpper),
              bollingerLower: toNumbers(series?.bollingerLower),
            }}
          />

          <div className="grid gap-3 md:grid-cols-2">
            <OscillatorChart
              title="RSI 14"
              domain={[0, 100]}
              references={[
                { value: 30, label: 'oversold' },
                { value: 70, label: 'overbought' },
              ]}
              lines={[
                { label: 'RSI', color: SERIES_COLORS.price, values: toNumbers(series?.rsi14) },
              ]}
              caption="Wilder smoothing. Dashed lines at 30 and 70; the flat start is the 14-bar warm-up, drawn as a break rather than a zero."
            />
            <OscillatorChart
              title="MACD 12 / 26 / 9"
              lines={[
                { label: 'MACD', color: SERIES_COLORS.price, values: toNumbers(series?.macd) },
                {
                  label: 'Signal',
                  color: SERIES_COLORS.fast,
                  values: toNumbers(series?.macdSignal),
                },
              ]}
              histogram={toNumbers(series?.macdHistogram)}
              caption="Histogram is MACD minus signal, green above zero and red below. The signal line starts later than MACD because it is an average of it."
            />
          </div>

          <IndicatorGrid snapshot={snapshot ?? null} />

          <div className="grid gap-3 md:grid-cols-2">
            <SessionPanel calendar={calendar} tradability={tradability} />
            <DataQualityPanel report={quality} />
          </div>
        </div>
      </div>
    </main>
  );
}
